config/routes.rb
Rails.application.routes.draw do
  namespace :administracao do
    resources :carga_horarias
  end

  namespace :administracao do
    resources :ambientes
  end

  namespace :administracao do
    resources :situacoes
  end

  namespace :administracao do
    resources :concursos
  end

  namespace :administracao do
    resources :classes
  end

  namespace :administracao do
    resources :quadros
  end

  namespace :administracao do
    resources :cargos
  end

  devise_for :usuarios
  resources :funcionarios

  get 'gerenciar/listagem_funcionarios'
  get 'gerenciar/criar_funcionario'
  get 'gerenciar/editar_funcionario'
  post 'gerenciar/salvar_funcionario'
  post 'gerenciar/atualizar_funcionario'
  get 'gerenciar/detalhes_funcionario'
  get 'gerenciar/relatorio_quantitativo_professor'
  get 'gerenciar/relatorio_quantitativo_nao_docente'
  get 'gerenciar/relatorio_nominal'
  get 'gerenciar/autocomplete_local_nome'
  resources :funcionarios do
    get :autocomplete_local_nome,:on=>:collection
    get :funcionario_professor
  end
  namespace :administracao do 
    resources :disciplinas
    resources :usuarios do
      get :autocomplete_local_nome,:on=>:collection
    end
    resources :locais
  end

  get '/', :to => 'gerenciar#listagem_funcionarios',:constraints => lambda{|req| req.env['warden'].user.try(:editor?)}
  #get '/', :to => 'gerenciar#listagem_funcionarios',:constraints => lambda{|req| req.env['warden'].user.try(:gestor_seed?)}
  #get '/', :to => 'gerenciar#listagem_funcionarios',:constraints => lambda{|req| req.env['warden'].user.try(:admin?)}
  root :to => 'funcionarios#index'
end

app/models/administracao.rb
module Administracao
  def self.table_name_prefix
    'administracao_'
  end
end

app/controllers/administracao/administracao_controller.rb
module Administracao
class AdministracaoController < ApplicationController
	before_action :dados,:gestores,:mudar_senha
  autocomplete :local, :nome, full: true
  def get_autocomplete_items(parameters)
    searchterm = params[:term]
    items = Local.secretarias.any_of({nome: Regexp.new(searchterm,Regexp::IGNORECASE) },{codigo: Regexp.new(searchterm,Regexp::IGNORECASE) })
  end

  def listagem_funcionarios
    if current_usuario.editor?
      @q = Funcionario.where(:usuario=>current_usuario).ransack(params[:q])
    else
      @q = Funcionario.ransack(params[:q])
    end
    @q.sorts = "nome asc" if @q.sorts.empty?
    @funcionarios = @q.result(distinct: true).asc.paginate(:page=>params[:page],:per_page=>10)
  end

  def relatorio_quantitativo_professor
   @disciplinas = Disciplina.asc(:nome)
   respond_to do |format|
    format.pdf { 
      send_data render_to_string, filename: 'foo.pdf', type: 'application/pdf', disposition: 'attachment'
    }
  end
end

def relatorio_quantitativo_nao_docente
 @funcionarios = Funcionario.where(:cargo.ne=>"Professor")
 respond_to do |format|
  format.pdf { 
    send_data render_to_string, filename: 'foo.pdf', type: 'application/pdf', disposition: 'attachment'
  }
end
end

def relatorio_nominal
end

def criar_funcionario
  @funcionario = Funcionario.new
  @titulo = "Cadastrar Funcionário"
  @caminho = administracao_salvar_funcionario_path
  render "editor"
end

def editar_funcionario
  @funcionario = Funcionario.find(params[:funcionario_id])
  @titulo = "Editar Funcionário"
  @caminho = administracao_atualizar_funcionario_path(:funcionario_id=>params[:funcionario_id])
  render "editor"
end

def salvar_funcionario
 @funcionario = Funcionario.new(funcionario_params)
 @titulo = "Cadastrar Funcionário"
 @caminho = administracao_salvar_funcionario_path
 respond_to do |format|
  if @funcionario.save
    format.html { redirect_to administracao_detalhes_funcionario_path(:funcionario_id=>@funcionario), notice: 'Funcionário cadastrado com sucesso' }
    format.json { render :show, status: :created, location: @funcionario }
  else
    format.html { render :editor }
    format.json { render json: @funcionario.errors, status: :unprocessable_entity }
  end
end
end

def atualizar_funcionario
  @funcionario = Funcionario.find(params[:funcionario_id])
  titulo = "Editar Funcionário"
  @caminho = administracao_atualizar_funcionario_path(:funcionario_id=>params[:funcionario_id])
  respond_to do |format|
    if @funcionario.update(funcionario_params)
      format.html { redirect_to administracao_detalhes_funcionario_path(:funcionario_id=>@funcionario.id), notice: 'Funcionário atualizado.' }
      format.json { render :show, status: :ok, location: @funcionario }
    else
      format.html { render :edit,:alert=>"Erros no cadastro, favor checar" }
      format.json { render json: @funcionario.errors, status: :unprocessable_entity }
    end
  end
end

def detalhes_funcionario
  @funcionario = Funcionario.find(params[:funcionario_id])
end
def funcionario_params
  params.require(:funcionario).permit([:local_id,:local_nome,:documento,:usuario_id,:componente_curricular,:nome, :cpf, :cadastro, :classe, :padrao, :turmas, :carga_horaria, :ambiente,:ambiente_nao_docente, :formacao, :ch_em_sala, :cargo, :quadro, :concurso, :area_concurso, :programa, :situacao, :local_id,:local, :disciplina_concurso, :disciplina_atuacao, :municipio_concurso])
end

end
end

app/controllers/administracao/ambientes_controller.rb
class Administracao::AmbientesController < ApplicationController
  before_action :set_administracao_ambiente, only: [:show, :edit, :update, :destroy]

  # GET /administracao/ambientes
  # GET /administracao/ambientes.json
  def index
    @q = Administracao::Ambiente.ransack((params[:q]))
    @ambientes = @q.result(distinct: true).order(:nome).paginate(:page=>params[:page],:per_page=>10)
  end

  # GET /administracao/ambientes/1
  # GET /administracao/ambientes/1.json
  def show
  end

  # GET /administracao/ambientes/new
  def new
    @administracao_ambiente = Administracao::Ambiente.new
  end

  # GET /administracao/ambientes/1/edit
  def edit
  end

  # POST /administracao/ambientes
  # POST /administracao/ambientes.json
  def create
    @administracao_ambiente = Administracao::Ambiente.new(administracao_ambiente_params)

    respond_to do |format|
      if @administracao_ambiente.save
        format.html { redirect_to @administracao_ambiente, notice: 'Ambiente was successfully created.' }
        format.json { render :show, status: :created, location: @administracao_ambiente }
      else
        format.html { render :new }
        format.json { render json: @administracao_ambiente.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /administracao/ambientes/1
  # PATCH/PUT /administracao/ambientes/1.json
  def update
    respond_to do |format|
      if @administracao_ambiente.update(administracao_ambiente_params)
        format.html { redirect_to @administracao_ambiente, notice: 'Ambiente was successfully updated.' }
        format.json { render :show, status: :ok, location: @administracao_ambiente }
      else
        format.html { render :edit }
        format.json { render json: @administracao_ambiente.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /administracao/ambientes/1
  # DELETE /administracao/ambientes/1.json
  def destroy
    @administracao_ambiente.destroy
    respond_to do |format|
      format.html { redirect_to administracao_ambientes_url, notice: 'Ambiente was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_administracao_ambiente
      @administracao_ambiente = Administracao::Ambiente.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def administracao_ambiente_params
      params.require(:administracao_ambiente).permit(:nome, :codigo)
    end
end

app/controllers/administracao/carga_horarias_controller.rb
class Administracao::CargaHorariasController < ApplicationController
  before_action :set_administracao_carga_horaria, only: [:show, :edit, :update, :destroy]

  # GET /administracao/carga_horarias
  # GET /administracao/carga_horarias.json
  def index
    @q = Administracao::CargaHoraria.ransack((params[:q]))
    @carga_horarias = @q.result(distinct: true).order(:nome).paginate(:page=>params[:page],:per_page=>10)
  end

  # GET /administracao/carga_horarias/1
  # GET /administracao/carga_horarias/1.json
  def show
  end

  # GET /administracao/carga_horarias/new
  def new
    @administracao_carga_horaria = Administracao::CargaHoraria.new
  end

  # GET /administracao/carga_horarias/1/edit
  def edit
  end

  # POST /administracao/carga_horarias
  # POST /administracao/carga_horarias.json
  def create
    @administracao_carga_horaria = Administracao::CargaHoraria.new(administracao_carga_horaria_params)

    respond_to do |format|
      if @administracao_carga_horaria.save
        format.html { redirect_to @administracao_carga_horaria, notice: 'Carga horaria was successfully created.' }
        format.json { render :show, status: :created, location: @administracao_carga_horaria }
      else
        format.html { render :new }
        format.json { render json: @administracao_carga_horaria.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /administracao/carga_horarias/1
  # PATCH/PUT /administracao/carga_horarias/1.json
  def update
    respond_to do |format|
      if @administracao_carga_horaria.update(administracao_carga_horaria_params)
        format.html { redirect_to @administracao_carga_horaria, notice: 'Carga horaria was successfully updated.' }
        format.json { render :show, status: :ok, location: @administracao_carga_horaria }
      else
        format.html { render :edit }
        format.json { render json: @administracao_carga_horaria.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /administracao/carga_horarias/1
  # DELETE /administracao/carga_horarias/1.json
  def destroy
    @administracao_carga_horaria.destroy
    respond_to do |format|
      format.html { redirect_to administracao_carga_horarias_url, notice: 'Carga horaria was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_administracao_carga_horaria
      @administracao_carga_horaria = Administracao::CargaHoraria.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def administracao_carga_horaria_params
      params.require(:administracao_carga_horaria).permit(:carga_horaria, :nome)
    end
end

app/controllers/administracao/cargos_controller.rb
class Administracao::CargosController < ApplicationController
  before_action :set_administracao_cargo, only: [:show, :edit, :update, :destroy]

  # GET /administracao/cargos
  # GET /administracao/cargos.json
 def index
    @q = Administracao::Cargo.ransack((params[:q]))
    @cargos = @q.result(distinct: true).order(:nome).paginate(:page=>params[:page],:per_page=>10)
  end

  # GET /administracao/cargos/1
  # GET /administracao/cargos/1.json
  def show
  end

  # GET /administracao/cargos/new
  def new
    @administracao_cargo = Administracao::Cargo.new
  end

  # GET /administracao/cargos/1/edit
  def edit
  end

  # POST /administracao/cargos
  # POST /administracao/cargos.json
  def create
    @administracao_cargo = Administracao::Cargo.new(administracao_cargo_params)

    respond_to do |format|
      if @administracao_cargo.save
        format.html { redirect_to @administracao_cargo, notice: 'Cargo was successfully created.' }
        format.json { render :show, status: :created, location: @administracao_cargo }
      else
        format.html { render :new }
        format.json { render json: @administracao_cargo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /administracao/cargos/1
  # PATCH/PUT /administracao/cargos/1.json
  def update
    respond_to do |format|
      if @administracao_cargo.update(administracao_cargo_params)
        format.html { redirect_to @administracao_cargo, notice: 'Cargo was successfully updated.' }
        format.json { render :show, status: :ok, location: @administracao_cargo }
      else
        format.html { render :edit }
        format.json { render json: @administracao_cargo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /administracao/cargos/1
  # DELETE /administracao/cargos/1.json
  def destroy
    @administracao_cargo.destroy
    respond_to do |format|
      format.html { redirect_to administracao_cargos_url, notice: 'Cargo was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_administracao_cargo
      @administracao_cargo = Administracao::Cargo.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def administracao_cargo_params
      params.require(:administracao_cargo).permit(:nome, :codigo)
    end
end

app/controllers/administracao/classes_controller.rb
class Administracao::ClassesController < ApplicationController
  before_action :set_administracao_classe, only: [:show, :edit, :update, :destroy]

  # GET /administracao/classes
  # GET /administracao/classes.json
 def index
    @q = Administracao::Classes.ransack((params[:q]))
    @classes = @q.result(distinct: true).order(:nome).paginate(:page=>params[:page],:per_page=>10)
  end

  # GET /administracao/classes/1
  # GET /administracao/classes/1.json
  def show
  end

  # GET /administracao/classes/new
  def new
    @administracao_classe = Administracao::Classe.new
  end

  # GET /administracao/classes/1/edit
  def edit
  end

  # POST /administracao/classes
  # POST /administracao/classes.json
  def create
    @administracao_classe = Administracao::Classe.new(administracao_classe_params)

    respond_to do |format|
      if @administracao_classe.save
        format.html { redirect_to @administracao_classe, notice: 'Classe was successfully created.' }
        format.json { render :show, status: :created, location: @administracao_classe }
      else
        format.html { render :new }
        format.json { render json: @administracao_classe.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /administracao/classes/1
  # PATCH/PUT /administracao/classes/1.json
  def update
    respond_to do |format|
      if @administracao_classe.update(administracao_classe_params)
        format.html { redirect_to @administracao_classe, notice: 'Classe was successfully updated.' }
        format.json { render :show, status: :ok, location: @administracao_classe }
      else
        format.html { render :edit }
        format.json { render json: @administracao_classe.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /administracao/classes/1
  # DELETE /administracao/classes/1.json
  def destroy
    @administracao_classe.destroy
    respond_to do |format|
      format.html { redirect_to administracao_classes_url, notice: 'Classe was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_administracao_classe
      @administracao_classe = Administracao::Classe.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def administracao_classe_params
      params.require(:administracao_classe).permit(:nome, :codigo)
    end
end

app/controllers/administracao/disciplinas_controller.rb
module Administracao
class DisciplinasController < ApplicationController
  before_action :set_disciplina, only: [:show, :edit, :update, :destroy]

  # GET /disciplinas
  # GET /disciplinas.json
def index
    @q = Administracao::Disciplina.ransack((params[:q]))
    @disciplinas = @q.result(distinct: true).order(:nome).paginate(:page=>params[:page],:per_page=>10)
  end

  # GET /disciplinas/1
  # GET /disciplinas/1.json
  def show
  end

  # GET /disciplinas/new
  def new
    @disciplina = Disciplina.new
  end

  # GET /disciplinas/1/edit
  def edit
  end

  # POST /disciplinas
  # POST /disciplinas.json
  def create
    @disciplina = Disciplina.new(disciplina_params)

    respond_to do |format|
      if @disciplina.save
        format.html { redirect_to @disciplina, notice: 'Disciplina was successfully created.' }
        format.json { render :show, status: :created, location: @disciplina }
      else
        format.html { render :new }
        format.json { render json: @disciplina.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /disciplinas/1
  # PATCH/PUT /disciplinas/1.json
  def update
    respond_to do |format|
      if @disciplina.update(disciplina_params)
        format.html { redirect_to @disciplina, notice: 'Disciplina was successfully updated.' }
        format.json { render :show, status: :ok, location: @disciplina }
      else
        format.html { render :edit }
        format.json { render json: @disciplina.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /disciplinas/1
  # DELETE /disciplinas/1.json
  def destroy
    @disciplina.destroy
    respond_to do |format|
      format.html { redirect_to disciplinas_url, notice: 'Disciplina was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_disciplina
      @disciplina = Disciplina.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def disciplina_params
      params.require(:disciplina).permit(:nome, :codigo)
    end
end
end

app/views/administracao/locais/_form.html.erb
<%= simple_form_for(@local) do |f| %>
<%= f.error_notification %>

<%= f.input :nome %>
<%= error_span(@local[:nome]) %>
<%= f.input :codigo %>
<%= error_span(@local[:codigo]) %>
<%= f.input :escola,:collection=>@boolean %>
<%= error_span(@local[:escola]) %>
<%= f.input :municipio,:collection=>@municipios %>
<%= error_span(@local[:municipio_id]) %>
<%= f.input :secretaria,:collection=>@boolean %>
<%= error_span(@local[:secretaria]) %>
<%= f.input :setorial,:collection=>@boolean %>
<%= error_span(@local[:setorial]) %>
<%#= f.input :local_pai_id %>
<%#= error_span(@local[:local_pai_id]) %>

<%= f.button :submit, :class => 'btn-primary' %>
<%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                administracao_locais_path, :class => 'btn btn-default' %>
<% end %>

app/views/administracao/locais/edit.html.erb
<%- model_class = Administracao::Local -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/administracao/locais/index.html.erb
<%- model_class = Administracao::Local -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>

<%= search_form_for @q,:url=>administracao_locais_path do |f| %>

<%= f.label "Busca" %>
<%= f.search_field :nome_or_codigo_cont %>
<%= f.submit %>
<% end %>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:nome) %></th>
      <th><%= model_class.human_attribute_name(:codigo) %></th>
      <th><%= model_class.human_attribute_name(:tipo) %></th>
      <th><%= model_class.human_attribute_name(:local_pai_id) %></th>
      <th><%= model_class.human_attribute_name(:municipio_id) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @locais.each do |local| %>
      <tr>
        <td><%= link_to local.id, administracao_local_path(local) %></td>
        <td><%= local.nome %></td>
        <td><%= local.codigo %></td>
        <td><%= local.tipo %></td>
        <td><%= local.local_pai_id %></td>
        <td><%= local.municipio_id %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_administracao_local_path(local), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      administracao_local_path(local),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>
<%= will_paginate @locais, renderer: BootstrapPagination::Rails,:previous_label=>"<",:next_label=>">"%><br/>
<%= link_to t('.new', :default => t("helpers.links.new")),
            new_administracao_local_path,
            :class => 'btn btn-primary' %>

app/views/administracao/locais/new.html.erb
<%- model_class = Administracao::Local -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/administracao/locais/show.html.erb
<%- model_class = Administracao::Local -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:nome) %>:</strong></dt>
  <dd><%= @local.nome %></dd>
  <dt><strong><%= model_class.human_attribute_name(:codigo) %>:</strong></dt>
  <dd><%= @local.codigo %></dd>
  <dt><strong><%= model_class.human_attribute_name(:tipo) %>:</strong></dt>
  <dd><%= @local.tipo %></dd>
  <dt><strong><%= model_class.human_attribute_name(:local_pai_id) %>:</strong></dt>
  <dd><%= @local.local_pai_id %></dd>
  <dt><strong><%= model_class.human_attribute_name(:municipio_id) %>:</strong></dt>
  <dd><%= @local.municipio_id %></dd>
</dl>

<%= link_to t('.back', :default => t("helpers.links.back")),
              administracao_locais_path, :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_administracao_local_path(@local), :class => 'btn btn-default' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              administracao_local_path(@local),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>