config/routes.rb
Rails.application.routes.draw do
  namespace :administracao do
    resources :carga_horarias
  end

  namespace :administracao do
    resources :ambientes
  end

  namespace :administracao do
    resources :situacoes
  end

  namespace :administracao do
    resources :concursos
  end

  namespace :administracao do
    resources :classes
  end

  namespace :administracao do
    resources :quadros
  end

  namespace :administracao do
    resources :cargos
  end

  devise_for :usuarios
  resources :funcionarios

  get 'gerenciar/listagem_funcionarios'
  get 'gerenciar/criar_funcionario'
  get 'gerenciar/editar_funcionario'
  post 'gerenciar/salvar_funcionario'
  post 'gerenciar/atualizar_funcionario'
  get 'gerenciar/detalhes_funcionario'
  get 'gerenciar/relatorio_quantitativo_professor'
  get 'gerenciar/relatorio_quantitativo_nao_docente'
  get 'gerenciar/relatorio_nominal'
  get 'gerenciar/autocomplete_local_nome'
  resources :funcionarios do
    get :autocomplete_local_nome,:on=>:collection
    get :funcionario_professor
  end
  namespace :administracao do 
    resources :disciplinas
    resources :usuarios do
      get :autocomplete_local_nome,:on=>:collection
    end
    resources :locais
  end

  get '/', :to => 'gerenciar#listagem_funcionarios',:constraints => lambda{|req| req.env['warden'].user.try(:editor?)}
  #get '/', :to => 'gerenciar#listagem_funcionarios',:constraints => lambda{|req| req.env['warden'].user.try(:gestor_seed?)}
  #get '/', :to => 'gerenciar#listagem_funcionarios',:constraints => lambda{|req| req.env['warden'].user.try(:admin?)}
  root :to => 'funcionarios#index'
end

app/models/funcionario.rb
class Funcionario < ActiveRecord::Base

  scope :do_quadro, ->(quadro) { where(:quadro_id => quadro) }
  scope :do_cargo, ->(cargo) { where(:cargo_id => cargo) }
  belongs_to :lotacao,class_name: "Administracao::Local"
  belongs_to :usuario
  belongs_to :ambiente,class_name: "Administracao::Ambiente"
  belongs_to :situacao,class_name: "Administracao::Situacao"
  belongs_to :concurso,class_name: "Administracao::Concurso"
  belongs_to :classe,class_name: "Administracao::Classe"
  belongs_to :cargo,class_name: "Administracao::Cargo"
  belongs_to :quadro,class_name: "Administracao::Quadro"
  belongs_to :carga_horaria,class_name: "Administracao::CargaHoraria"
  belongs_to :disciplina_concurso,:class_name=>"Administracao::Disciplina",:inverse_of=>:funcionarios
  belongs_to :disciplina_atuacao,:class_name=>"Administracao::Disciplina",:inverse_of=>:funcionarios_atuando
  belongs_to :municipio_opcao,:class_name=>"Municipio"
  validate :validar_local
  validates_presence_of :nome,:cpf,:cargo,:carga_horaria,:quadro,message: "Informação necessária"
  validates_presence_of :classe_id,:municipio_opcao_id,:situacao_id,:concurso_id,if:  Proc.new { |a| self.quadro and self.quadro.nome=="Estadual"},message: "Informação necessária"
  validates_presence_of :ambiente,message: "Informação necessária",:if=>Proc.new{|a|a.lotacao and a.situacao and a.lotacao.escola? and (a.situacao.nome.include?("Ativo") or a.situacao.nome.include?("Acompanhado"))}
  validates_presence_of :disciplina_concurso_id,if:  Proc.new { |a|a.cargo and a.quadro and a.cargo.nome=="Professor" and (self.quadro.nome=="Estadual" or self.quadro.nome=="Federal")},message: "Informação necessária"
  validates_presence_of :disciplina_atuacao_id,if:  Proc.new { |a| a.cargo and a.cargo.nome=="Professor" and a.ambiente and a.situacao and a.ambiente.nome=="Sala de Aula" and (self.situacao.nome.include? "Ativo" or self.situacao.nome.include? "Acompanhado")}
  validate :validar_tudo
  validate :cpf_valido
  delegate :nome, to: :lotacao, prefix: true, :allow_nil => true

  #Validaçoes antigas
  #validates_presence_of :cadastro,if:  Proc.new { |a| !a.quadro=="Contrato Administrativo"},message: "Informação necessária"

  validates_uniqueness_of :cadastro,scope: :lotacao,:if=>Proc.new { |a|a.quadro and !a.quadro.nome.include?("Contrato")},message: "Já está cadastrado"
  validates_uniqueness_of :cpf,scope: :cadastro,:if=>Proc.new { |a|a.quadro and !a.quadro.nome.include?("Contrato")},message: "Já está cadastrado"
  validates_uniqueness_of :cpf,:if=>Proc.new { |a|a.quadro and a.quadro.nome.include?("Contrato")},message: "Já está cadastrado"
  validate :validate_cadastro
  before_save :nome_maiusculo

  def cpf_valido
    cpf = Cpf.new(self.cpf)
    if !cpf.valido?
     errors.add(:cpf, "não é valido")
   end
 end


 def validar_tudo
  if self.cargo.nil?
    errors.add(:cargo_id, "Informação necessária")
  elsif self.quadro.nil?
    errors.add(:quadro_id, "Informação necessária")
  elsif self.cargo.nil? and self.quadro.nil?
    errors.add(:cargo_id, "Informação necessária")
    errors.add(:quadro_id, "Informação necessária")
  elsif self.ambiente and self.situacao and (self.situacao.nome.include? "Ativo" or self.situacao.nome.include? "Acompanhado") and self.ambiente.nome=="Sala de Aula" and self.cargo and self.quadro and self.cargo.nome=="Professor" and self.disciplina_atuacao.nil?
   errors.add(:disciplina_atuacao_id, "Informação necessária")
 elsif self.quadro and self.quadro.nome!="Contrato Administrativo" and self.cargo and self.quadro and self.cargo.nome=="Professor" and self.disciplina_concurso.nil?
   errors.add(:disciplina_concurso_id, "Informação necessária")
 #elsif self.cargo and self.quadro and self.cargo.nome=="Professor" and self.disciplina_concurso.nil?
   #errors.add(:disciplina_concurso_id, "Informação necessária")
 end
end

def validar_local
  if self.lotacao.nil?
    errors.add(:lotacao_id, "Informação necessária")
  end
end

def validate_cadastro
  if self.quadro and self.cadastro.blank? and !self.quadro.nome.include?("Contrato")
    errors.add(:cadastro, "Informação necessária")
  end
end

def pos_ambiente
  if !self.ambiente_nao_docente.blank? and self.cargo!="Professor"
    self.ambiente = self.ambiente_nao_docente
  elsif self.ambiente_nao_docente.blank? and self.cargo!="Professor"
    self.ambiente = ""
  end
end

def nome_maiusculo
  if !self.nome.blank?
    self.nome = self.nome.upcase
  end
end

end

app/controllers/funcionarios_controller.rb
class FuncionariosController < ApplicationController
  before_action :set_funcionario, only: [:show, :edit, :update, :destroy]
  before_action :mudar_senha,:dados
  autocomplete :local, :nome, full: true,:class_name=>Administracao::Local

  # GET /funcionarios
  # GET /funcionarios.json
  def index
    @funcionarios = Funcionario.where(:lotacao_id=>current_usuario.lotacao_id)
  end

  # GET /funcionarios/1
  # GET /funcionarios/1.json
  def show
  end

  # GET /funcionarios/new
  def new
    @funcionario = Funcionario.new
  end

  # GET /funcionarios/1/edit
  def edit
  end

  # POST /funcionarios
  # POST /funcionarios.json
  def create
    @funcionario = Funcionario.new(funcionario_params)

    respond_to do |format|
      if @funcionario.save!
        format.html { redirect_to @funcionario, notice: 'Funcionário Cadastrado com Sucesso.' }
        format.json { render :show, status: :created, location: @funcionario }
      else
        format.html { render :new }
        format.json { render json: @funcionario.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /funcionarios/1
  # PATCH/PUT /funcionarios/1.json
  def update
    respond_to do |format|
      if @funcionario.update(funcionario_params)
        format.html { redirect_to @funcionario, notice: 'Funcionário Atualizado com Sucesso.' }
        format.json { render :show, status: :ok, location: @funcionario }
      else
        format.html { render :edit }
        format.json { render json: @funcionario.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /funcionarios/1
  # DELETE /funcionarios/1.json
  def destroy
    @funcionario.destroy
    respond_to do |format|
      format.html { redirect_to funcionarios_url, alert: 'Funcionário Apagado com Sucesso.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_funcionario
      @funcionario = Funcionario.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def funcionario_params
      #params.require(:funcionario).permit(:nome, :cpf, :cadastro, :componente_curricular, :documento_movimentacao, :carga_horaria_id, :classe_id, :cargo_id, :lotacao_id, :quadro_id, :concurso_id, :municipio_opcao_id, :situacao_id, :usuario_id, :disciplina_concurso_id, :disciplina_atuacao_id)
      params.require(:funcionario).permit!
    end
end

app/helpers/funcionarios_helper.rb
module FuncionariosHelper
	def carga_horaria(obj)
		if (obj.is_a?(String) or obj.is_a?(Integer)) and !obj.blank?
			return "#{obj} Horas"
		else
			return "Nada Cadastrado"
		end
	end

	def ambiente_alerta(obj)
		if obj.local.escola and obj.ambiente.blank? and (obj.situacao=="Ativo" or obj.situacao=="Acompanhado pela Casa do Professor" or obj.situacao=="Ativo mas em sala ambiente perante perícia médica")
			return raw "<b style='color: red;'>Nada cadastrado</b>"
		elsif !obj.ambiente.blank?
			return obj.ambiente
			else
				return "Nada Cadastrado"
		end
	end
end

app/views/funcionarios/_form_escola.html.erb
<%= simple_form_for @funcionario, :html => { :class => 'form-condensed' } do |f| %>

<%= f.input :lotacao_id,:as=>:hidden,:input_html=>{:value=>current_usuario.lotacao_id} %>

<%= f.input :nome %>
<%= error_span(@funcionario[:nome]) %>
<%= f.input :cpf,:label=>"CPF",:input_html=>{:class=>"cpf"} %>
<%= error_span(@funcionario[:cpf]) %>
<%= f.label "Cadastro¹"%> <i>¹não é necessário preencher este campo para o Contrato Administrativo.</i>
<%= f.input :cadastro,:label=>false%>
<%= error_span(@funcionario[:cadastro]) %>
<%= f.input :cargo_id,:collection=>@cargos,:label=>"Cargo"%>
<div class="js-dependent-fields" data-select-id='funcionario_cargo' data-option-value='<%= Administracao::Cargo.where(:nome=>"Professor").first.id%>'>
		<% if @funcionario.disciplina_concurso%>
		<%= f.input :disciplina_concurso_id,:label=>"Disciplina do Concurso/Contrato",:collection=>@disciplinas,:selected=>@funcionario.disciplina_concurso_id%>
		<% else %>
		<%= f.input :disciplina_concurso_id,:label=>"Disciplina do Concurso/Contrato",:collection=>@disciplinas%>
		<% end %>
		<%= error_span(@funcionario[:disciplina_concurso]) %>
	</div>
<%= error_span(@funcionario[:cargo]) %>
<%= f.input :quadro_id,:collection=>@quadros %>

<%= error_span(@funcionario[:quadro]) %>
<div class="js-dependent-fields" data-select-id='funcionario_quadro_id' data-option-value='<%= Administracao::Quadro.where(:nome=>"Estadual").first.id%>|<%= Administracao::Quadro.where(:nome=>"Federal").first.id%>'>
	<%= f.input :classe_id,:collection=>@classes %>
	<%= error_span(@funcionario[:classe_id]) %>
	<% if @funcionario.municipio_opcao%>
	<%= f.input :municipio_opcao_id,:label=>"Município do Concurso",:collection=>@municipios,:selected=>@funcionario.municipio_opcao_id%>
	<% else %>
	<%= f.input :municipio_opcao_id,:label=>"Município do Concurso",:collection=>@municipios%>
	<% end %>
	<%= error_span(@funcionario[:municipio_opcao]) %>
	<%= f.input :situacao_id,:label=>"Situação",:collection=>@situacoes %>
	<%= error_span(@funcionario[:situacao]) %>
</div>
<div class="js-dependent-fields" data-select-id='funcionario_quadro_id' data-option-value='<%= Administracao::Quadro.where(:nome=>"Estadual").first.id%>'>
	<%= f.input :concurso_id,:collection=>@concursos %>
	<%= error_span(@funcionario[:concurso_id]) %>
</div>
<%= f.input :carga_horaria_id,:collection=>@cargas_horarias,:label=>"Carga Horária do vínculo" %>
<%= error_span(@funcionario[:carga_horaria]) %>

<%= f.input :ambiente_id,:collection=>@ambientes %>
<%= error_span(@funcionario[:ambiente]) %>


<div class="js-dependent-fields" data-select-id='funcionario_ambiente_id' data-option-value='<%= Administracao::Ambiente.where(:nome=>'Sala de Aula').first.id%>'>
	<%if @funcionario.disciplina_atuacao%>
	<%= f.input :disciplina_atuacao_id,:collection=>@disciplinas,:selected=>@funcionario.disciplina_atuacao_id %>
	<%else%>
	<%= f.input :disciplina_atuacao_id,:collection=>@disciplinas%>
	<%end%>
	
	<%= error_span(@funcionario[:disciplina_atuacao]) %>
	<div class="js-dependent-fields" data-select-id='funcionario_disciplina_atuacao_id' data-option-value='<%= Administracao::Disciplina.where(:nome=>"Educação Profissional").first.id%>'>
		<%= f.label "Componente Curricular²"%> <i>² Somente para educação Profissional</i>
		<%= f.input :componente_curricular,:label=>false%>
	</div>
	<%= f.input :turmas,:label=>"Numero de Turmas",:as=>:integer %>
	<%= error_span(@funcionario[:turmas]) %>
	<%= f.input :ch_em_sala,:label=>"Carga Horária em sala",:as=>:integer %>
	<%= error_span(@funcionario[:ch_em_sala]) %>
</div>
<div class="js-dependent-fields" data-select-id='funcionario_ambiente_id' data-option-value='Coordenação de Programa Estadual|Coordenação de Programa Federal'>
	<%#= f.input :programa,:label=>"Nome do Programa" %>
	<%= error_span(@funcionario[:programa]) %>
</div>
<%#= f.input :local,:url=>autocomplete_local_nome_funcionarios_path,:as=>:autocomplete %>


<%= f.button :submit, :class => 'btn-primary' %>
<%= link_to t('.cancel', :default => t("helpers.links.cancel")),
funcionarios_path, :class => 'btn btn-default' %>
<% end %>

app/views/funcionarios/_form_secretaria.html.erb
<%= simple_form_for @funcionario, :html => { :class => 'form-condensed' } do |f| %>

<%= f.input :lotacao_id,:as=>:hidden,:input_html=>{:value=>current_usuario.lotacao_id} %>

<%= f.input :nome %>
<%= error_span(@funcionario[:nome]) %>
<%= f.input :cpf,:label=>"CPF",:input_html=>{:class=>"cpf"} %>
<%= error_span(@funcionario[:cpf]) %>
<%= f.label "Cadastro¹"%> <i>¹não é necessário preencher este campo para o Contrato Administrativo.</i>
<%= f.input :cadastro,:label=>false%>
<%= error_span(@funcionario[:cadastro]) %>
<%= f.input :cargo,:collection=>@cargos,:label=>"Cargo"%>
<%= error_span(@funcionario[:cargo]) %>
<div class="js-dependent-fields" data-select-id='funcionario_cargo' data-option-value='<%=Administracao::Cargo.find_by(:nome=>"Professor").id%>'>
	<%= f.input :disciplina_concurso_id,:label=>"Disciplina do Concurso/Contrato",:collection=>@disciplinas%>
	<%= error_span(@funcionario[:disciplina_concurso]) %>
</div>
<%= f.input :quadro,:collection=>@quadros %>
<%= error_span(@funcionario[:quadro]) %>
<div class="js-dependent-fields" data-select-id='funcionario_quadro_id' data-option-value='<%=Administracao::Quadro.find_by(:nome=>"Estadual").id%>|<%=Administracao::Quadro.find_by(:nome=>"Federal").id%>'>
	<%= f.input :classe,:collection=>@classes %>
	<%= error_span(@funcionario[:classe]) %>
	<%= f.input :municipio_opcao,:label=>"Município do Concurso",:collection=>@municipios%>
	<%= error_span(@funcionario[:municipio_opcao]) %>
	<%= f.input :situacao,:label=>"Situação",:collection=>@situacoes %>
	<%= error_span(@funcionario[:situacao]) %>
</div>
<div class="js-dependent-fields" data-select-id='funcionario_quadro' data-option-value='<%=Administracao::Quadro.find_by(:nome=>"Estadual").id%>'>
	<%= f.input :concurso_id,:collection=>@concursos %>
	<%= error_span(@funcionario[:concurso]) %>
</div>
<%= f.input :carga_horaria,:collection=>@cargas_horarias,:label=>"Carga Horária do vínculo" %>
<%= error_span(@funcionario[:carga_horaria]) %>


<%= f.button :submit, :class => 'btn-primary' %>
<%= link_to t('.cancel', :default => t("helpers.links.cancel")),
funcionarios_path, :class => 'btn btn-default' %>
<% end %>

app/views/funcionarios/edit.html.erb
<%- model_class = Funcionario -%>
<%content_for :header do%>
<%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %>
<% end %>
<%= render :partial => 'form_escola' if current_usuario.lotacao.escola?%>
<%= render :partial => 'form_secretaria' if current_usuario.lotacao.setorial? or current_usuario.lotacao.secretaria?%>

app/views/funcionarios/index.html.erb
<%- model_class = Funcionario -%>
<%content_for :header do%>
<%=t '.title', :default => model_class.model_name.human.pluralize.titleize %>
<% end %>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:nome) %></th>
      <th><%= model_class.human_attribute_name(:cpf) %></th>
      <th><%= model_class.human_attribute_name(:cadastro) %></th>
      <th><%= model_class.human_attribute_name(:carga_horaria) %></th>
      <% if current_usuario.lotacao.escola?%>
      <th><%= model_class.human_attribute_name(:ambiente) %></th>
      <%end%>
      <th><%= model_class.human_attribute_name(:cargo) %></th>
      <th><%= model_class.human_attribute_name(:quadro) %></th>
      <th><%= model_class.human_attribute_name(:situacao) %></th>
      <th><%= model_class.human_attribute_name(:disciplina_concurso_id) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @funcionarios.each do |funcionario| %>
      <tr>
        <td><%= link_to funcionario.nome,funcionario_path(funcionario) %></td>
        <td><%= objeto_valor(funcionario.cpf) %></td>
        <td><%= objeto_valor(funcionario.cadastro) %></td>
        <td><%= objeto_valor(funcionario.carga_horaria) %></td>
        <% if current_usuario.lotacao.escola?%>
        <td><%= objeto_valor(funcionario.ambiente) %></td>
        <% end %>
        <td><%= objeto_valor(funcionario.cargo) %></td>
        <td><%= objeto_valor(funcionario.quadro) %></td>
        <td><%= objeto_valor(funcionario.situacao) %></td>
        <td><%= objeto_valor(funcionario.disciplina_concurso) %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_funcionario_path(funcionario), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      funcionario_path(funcionario),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_funcionario_path,
            :class => 'btn btn-success' %>

app/views/funcionarios/index_editor.html.erb
<%- model_class = Funcionario -%>
<%content_for :header do%>
<%=t '.title', :default => model_class.model_name.human.pluralize.titleize %>
<% end %>
<%= form_for @q,:url=>administracao_listagem_funcionarios_path,:method=>:get do |f| %>

<%= f.label "Busca" %>
<%= f.text_field :nome_or_cpf_or_cadastro_cont %>
<%= f.select :quadro_cont,@quadros,include_blank: "Buscar por quadro",:selected=>:blank %>
<%= f.submit %>
<% end %>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:nome) %></th>
      <th><%= model_class.human_attribute_name(:cpf) %></th>
      <th><%= model_class.human_attribute_name(:cadastro) %></th>
      <th><%= model_class.human_attribute_name(:carga_horaria) %></th>
      <th><%= model_class.human_attribute_name(:ambiente) %></th>
      <th><%= model_class.human_attribute_name(:cargo) %></th>
      <th><%= model_class.human_attribute_name(:quadro) %></th>
      <th><%= model_class.human_attribute_name(:lotação) %></th>
      <th><%= model_class.human_attribute_name(:disciplina_concurso_id) %></th>
      <% if !current_usuario.admin?%>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
      <% end %>
    </tr>
  </thead>
  <tbody>
    <% @funcionarios.each do |funcionario| %>
      <tr>
        <td><%= link_to funcionario.nome,funcionario_path(funcionario) %></td>
        <td><%= objeto_valor(funcionario.cpf) %></td>
        <td><%= objeto_valor(funcionario.cadastro) %></td>
        <td><%= objeto_valor(funcionario.carga_horaria) %></td>
        <td><%= ambiente_alerta(funcionario) %></td>
        <td><%= objeto_valor(funcionario.cargo) %></td>
        <td><%= objeto_valor(funcionario.quadro) %></td>
        <td><%= objeto_valor(funcionario.local).upcase %></td>
        <td><%= objeto_valor(funcionario.disciplina_concurso) %></td>
         <% if !current_usuario.admin?%>
        <td>
        <%= link_to t('.show', :default => t("helpers.links.show")),
       funcionario_path(funcionario), :class => 'btn btn-default btn-xs' if current_usuario.admin?%>
        <%= link_to t('.edit', :default => t("helpers.links.edit")),
        edit_funcionario_path(funcionario), :class => 'btn btn-default btn-xs' if current_usuario.admin?%>
        <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
        funcionario_path(funcionario),
        :method => :delete,
        :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
        :class => 'btn btn-xs btn-danger' if current_usuario.admin?%>
      </td>
      <% end %>
      </tr>
    <% end %>
  </tbody>
</table>
<%= will_paginate @funcionarios, renderer: BootstrapPagination::Rails,:previous_label=>"<",:next_label=>">",:total_entries=>true%><br/>
<%= link_to t('.new', :default => t("helpers.links.new")),
            new_funcionario_path,
            :class => 'btn btn-success' %>

app/views/funcionarios/new.html.erb
<%- model_class = Funcionario -%>
<%content_for :header do%>
 <%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %>
<% end %>
<%= render :partial => 'form_escola' if current_usuario.lotacao.escola?%>
<%= render :partial => 'form_secretaria' if current_usuario.lotacao.setorial?%>

app/views/funcionarios/show.html.erb
<%- model_class = Funcionario -%>
<%content_for :header do%>
<%=t '.title', :default => model_class.model_name.human.titleize %>
<% end %>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:nome) %>:</strong></dt>
  <dd><%= objeto_valor(@funcionario.nome) %></dd>
  <dt><strong><%= model_class.human_attribute_name(:cpf) %>:</strong></dt>
  <dd><%= objeto_valor(@funcionario.cpf) %></dd>
  <dt><strong><%= model_class.human_attribute_name(:cadastro) %>:</strong></dt>
  <dd><%= objeto_valor(@funcionario.cadastro) %></dd>
  <dt><strong><%= model_class.human_attribute_name(:classe) %>:</strong></dt>
  <dd><%= objeto_valor(@funcionario.classe) %></dd>
  <dt><strong><%= model_class.human_attribute_name(:carga_horaria) %>:</strong></dt>
  <dd><%= objeto_valor(@funcionario.carga_horaria) %></dd>
  <%if @funcionario.lotacao.escola?%>
  <dt><strong><%= model_class.human_attribute_name(:ambiente) %>:</strong></dt>
  <dd><%= objeto_valor(@funcionario) %></dd>
  <%end%>
  <dt><strong><%= model_class.human_attribute_name(:cargo) %>:</strong></dt>
  <dd><%= objeto_valor(@funcionario.cargo) %></dd>
  <dt><strong><%= model_class.human_attribute_name(:quadro) %>:</strong></dt>
  <dd><%= objeto_valor(@funcionario.quadro) %></dd>
  <dt><strong><%= model_class.human_attribute_name(:concurso) %>:</strong></dt>
  <dd><%= objeto_valor(@funcionario.concurso) %></dd>
  <% if @funcionario.cargo and @funcionario.cargo.nome.include?("Programa")%>
  <dt><strong><%= model_class.human_attribute_name(:programa) %>:</strong></dt>
  <dd><%= objeto_valor(@funcionario.programa) %></dd>
  <% end %>
  <dt><strong><%= model_class.human_attribute_name(:situacao) %>:</strong></dt>
  <dd><%= objeto_valor(@funcionario.situacao) %></dd>
  <dt><strong><%= model_class.human_attribute_name("Município de Concurso") %>:</strong></dt>
  <dd><%= objeto_valor(@funcionario.municipio_opcao) %></dd>
  <%if @funcionario.cargo and @funcionario.cargo.nome=="Professor"%>
  <dt><strong><%= model_class.human_attribute_name(:disciplina_concurso_id) %>:</strong></dt>
  <dd><%= objeto_valor(@funcionario.disciplina_concurso) %></dd>
  <% end %>
  <%if @funcionario.lotacao.escola?%>
  <dt><strong><%= model_class.human_attribute_name(:disciplina_atuacao_id) %>:</strong></dt>
  <dd><%= objeto_valor(@funcionario.disciplina_atuacao) %></dd>
  <% if @funcionario.disciplina_atuacao and @funcionario.disciplina_atuacao.nome=="Educação Profissional"%>
  <dt><strong><%= model_class.human_attribute_name(:nome) %>:</strong></dt>
  <dd><%= objeto_valor(@funcionario.componente_curricular) %></dd>
  <%end%>
  <dt><strong><%= model_class.human_attribute_name(:turmas) %>:</strong></dt>
  <dd><%= objeto_valor(@funcionario.turmas) %></dd>
  <dt><strong><%= model_class.human_attribute_name(:ch_em_sala) %>:</strong></dt>
  <dd><%= carga_horaria(@funcionario.ch_em_sala) %></dd>
  <%end%>
  
</dl>

<%= link_to t('.back', :default => t("helpers.links.back")),
funcionarios_path, :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
edit_funcionario_path(@funcionario), :class => 'btn btn-default' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
funcionario_path(@funcionario),
:method => 'delete',
:data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
:class => 'btn btn-danger' %>