config/routes.rb
Rails.application.routes.draw do
  namespace :administracao do
    resources :carga_horarias
  end

  namespace :administracao do
    resources :ambientes
  end

  namespace :administracao do
    resources :situacoes
  end

  namespace :administracao do
    resources :concursos
  end

  namespace :administracao do
    resources :classes
  end

  namespace :administracao do
    resources :quadros
  end

  namespace :administracao do
    resources :cargos
  end

  devise_for :usuarios
  resources :funcionarios

  get 'gerenciar/listagem_funcionarios'
  get 'gerenciar/criar_funcionario'
  get 'gerenciar/editar_funcionario'
  post 'gerenciar/salvar_funcionario'
  post 'gerenciar/atualizar_funcionario'
  get 'gerenciar/detalhes_funcionario'
  get 'gerenciar/relatorio_quantitativo_professor'
  get 'gerenciar/relatorio_quantitativo_nao_docente'
  get 'gerenciar/relatorio_nominal'
  get 'gerenciar/autocomplete_local_nome'
  resources :funcionarios do
    get :autocomplete_local_nome,:on=>:collection
    get :funcionario_professor
  end
  namespace :administracao do 
    resources :disciplinas
    resources :usuarios do
      get :autocomplete_local_nome,:on=>:collection
    end
    resources :locais
  end

  get '/', :to => 'gerenciar#listagem_funcionarios',:constraints => lambda{|req| req.env['warden'].user.try(:editor?)}
  #get '/', :to => 'gerenciar#listagem_funcionarios',:constraints => lambda{|req| req.env['warden'].user.try(:gestor_seed?)}
  #get '/', :to => 'gerenciar#listagem_funcionarios',:constraints => lambda{|req| req.env['warden'].user.try(:admin?)}
  root :to => 'funcionarios#index'
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title><%= content_for?(:title) ? yield(:title) : "SEED e Você, fazendo a educação!" %></title>
  <%= csrf_meta_tags %>

  <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
      <![endif]-->

      <%= stylesheet_link_tag "application", :media => "all" %>

      <!-- For third-generation iPad with high-resolution Retina display: -->
      <!-- Size should be 144 x 144 pixels -->
      <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

      <!-- For iPhone with high-resolution Retina display: -->
      <!-- Size should be 114 x 114 pixels -->
      <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

      <!-- For first- and second-generation iPad: -->
      <!-- Size should be 72 x 72 pixels -->
      <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

      <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
      <!-- Size should be 57 x 57 pixels -->
      <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

      <!-- For all other devices -->
      <!-- Size should be 32 x 32 pixels -->
      <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

      <%= javascript_include_tag "application" %>
    </head>
    <!-- Modal -->
    <%= render :partial=>"devise/shared/modal_login" if current_usuario.nil?%>
    <body>
      <div class="navbar navbar-default navbar-fixed-top">
       <a class="navbar-left"><%=image_tag("logo_governo.png")%></a>
       <div class="navbar-collapse collapse navbar-responsive-collapse">
         <ul class="nav navbar-nav navbar-fixed navbar-right" style="margin-right: 10px;">
          <%= render 'devise/shared/menu' if usuario_signed_in?%>
          <%= render 'devise/shared/menu_login' if current_usuario.nil?%>
        </ul>
         <ul class="nav navbar-nav navbar-fixed navbar-right" style="margin-right: 10px;">
           <%= render 'shared/menu_relatorios' if usuario_signed_in? and (current_usuario.gestor_seed? or current_usuario.admin?)%>
         </ul>
      </div>
    </div>
    <% if usuario_signed_in? and current_usuario.alerta_ambiente%>
    <h4 class="alert alert-danger container" role="alert" style="margin-top: 4%; width: 98%;">Os funcionários com a informação marcada em vermelho precisam ser revistos.</h4>
    <div class="container panel panel-default" style="margin-top: 1%; margin-left: 1%; width:98%;">
      <%else%>
      <div class="container panel panel-default" style="margin-top: 4%; margin-left: 1%; width:98%;">
        <% end %>

        <div class="row">
          <div class="col-lg-12">
           <div class="panel-body">
             <div class="page-header">
               <h1><%= yield :header%></h1>
             </div>

             <%= bootstrap_flash %>
             <%= yield %>
           </div>
         </div>
       </div>
     </div><!--/row-->



   </div> <!-- /container -->

   <footer class="footer navbar-fixed-bottom">
    <div class="container panel panel-default">
      <p class="text-muted text-center">SEED e Você, fazendo a educação!</p>
    </div>
  </footer>

</body>
</html>